name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run general-setup.sh
        run: ./general-setup.sh
